/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  * here we are making pc13 oin high through resisters
  ******************************************************************************
*/

#include<stdint.h>
#include<stdio.h>
#include"main.h"

int main(void)
{
	//uint32_t volatile *ClkCtrReg  = (uint32_t*)0x40021018;

	uint32_t volatile *PortCModeReg  = (uint32_t*)0x40011004;
	uint32_t volatile *PortAModeReg  = (uint32_t*)0x40010800;

	uint32_t volatile *PortCOutReg  = (uint32_t*)0x4001100c;
	uint32_t volatile *PortAInReg  = (uint32_t*)0x40010808;


	// *ClkCtrReg = *ClkCtrReg|(1<<4);
	//*ClkCtrReg = *ClkCtrReg|(1<<2);

	ClkCtrReg_t volatile *clk = (ClkCtrReg_t*) 0x40021018;
	clk->GPIOAEN = 1;
	clk->GPIOCEN = 1;

	*PortCModeReg = *PortCModeReg & ~(3<<20);
	*PortCModeReg = *PortCModeReg | (1<<20);	//led on after mode define automatically
	*PortCOutReg = *PortCOutReg | (1<<13);	//led off


	*PortAModeReg = *PortAModeReg & ~(3<<0);
	//*PortAInReg = 0x00000001;


	while(1){
		uint8_t data = (uint8_t) (*PortAInReg & 0x00000001);
		if(data){
			*PortCOutReg = *PortCOutReg & (0);	//led on
		}
		else{
			*PortCOutReg = *PortCOutReg | (1<<13);	//led off
		}
	}
	//*PortdOutReg = *PortdOutReg | 0x00002000;





	while(1);
}
