/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  * here we are making pc13 oin high through resisters
  ******************************************************************************
*/

#include<stdint.h>
#include<stdio.h>

int main(void)
{
	uint32_t *ClkCtrReg  = (uint32_t*)0x40021018;
	uint32_t *PortDModeReg  = (uint32_t*)0x40011004;
	uint32_t *PortdOutReg  = (uint32_t*)0x4001100c;

	*ClkCtrReg = *ClkCtrReg|0x00000010;

	*PortDModeReg = *PortDModeReg & 0xffcfffff;
	*PortDModeReg = *PortDModeReg | 0x00100000;	//led on after mode define automatically

	*PortdOutReg = *PortdOutReg | 0x00002000;	//led off
	*PortdOutReg = *PortdOutReg & 0x00000000;	//led on
	//*PortdOutReg = *PortdOutReg | 0x00002000;


	while(1);
}
